name: AgroCore Frontend CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Versión estable y recomendada para Next.js
          cache: 'npm'       # Esto hace que las instalaciones futuras vuelen

      - name: Instalar dependencias de forma limpia
        run: npm ci

      - name: Revisar calidad del código (Linting)
        run: npm run lint

      - name: Compilar el proyecto (Build)
        run: npm run build